SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_FPS = 60

COLOR_WHITE = "white"
COLOR_BLACK = "black"
COLOR_RED =   "red"

ASTEROID_X_AXIS_MIN_VELOCITY_RIGHT = 50
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_POLYGON_LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200