# Imports
from CONSTS.COLORS import *

# MENU CONSTANTS
MENU_STATES_LIST = ['Start Game', 'Controls', 'Exit', 'Credits']
MENU_TITLE_TEXT = 'ASTEROIDS 2085'
MENU_MUSIC_VOLUME = 0.1
MENU_TITLE_FADE_SPEED = 1.5
MENU_TITLE_FONT_SIZE = 100
MENU_OPTION_FONT_SIZE = 50
MENU_OPTION_COLOR = COLOR_RED
MENU_OPTION_SELECTED_COLOR = COLOR_YELLOW
MENU_OPTION_ARROW_COLOR = COLOR_WHITE
MENU_OPTION_SPACING = 50 # DONT CHANGE THIS unless you know what you are doing
MENU_OPTION_ARROW_SIZE = 20 # TODO: NOT IMPLEMENTED YET (NO REFERENCES... YET)
MENU_OPTION_ARROW_SPACING = 30 # TODO: NOT IMPLEMENTED YET (NO REFERENCES... YET)
MENU_OPTION_ARROW_OFFSET = 50 # TODO: NOT IMPLEMENTED YET (NO REFERENCES... YET)
MENU_TRANSITION_SPEED = 2  # Alpha change per frame
MENU_TRANSITION_DURATION = 0.5  # seconds